
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Delete(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Get~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Get(System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Post(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Put(System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Startup.ConfigureAuth(Owin.IAppBuilder)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.HelpPageSampleGenerator.GetActionSample(System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.Type,System.Net.Http.Formatting.MediaTypeFormatter,System.Net.Http.Headers.MediaTypeHeaderValue,DesenvolvimentoWebModuloII.Areas.HelpPage.SampleDirection)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Delete(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Get(System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Post(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.ValuesController.Put(System.Int32,System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.AddExternalLogin(DesenvolvimentoWebModuloII.Models.AddExternalLoginBindingModel)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.ChangePassword(DesenvolvimentoWebModuloII.Models.ChangePasswordBindingModel)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.GetExternalLogin(System.String,System.String)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.GetManageInfo(System.String,System.Boolean)~System.Threading.Tasks.Task{DesenvolvimentoWebModuloII.Models.ManageInfoViewModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.Register(DesenvolvimentoWebModuloII.Models.RegisterBindingModel)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.RegisterExternal(DesenvolvimentoWebModuloII.Models.RegisterExternalBindingModel)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.RemoveLogin(DesenvolvimentoWebModuloII.Models.RemoveLoginBindingModel)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:Async method can be terminating with 'Async' name.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Controllers.AccountController.SetPassword(DesenvolvimentoWebModuloII.Models.SetPasswordBindingModel)~System.Threading.Tasks.Task{System.Web.Http.IHttpActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0004:Catch block cannot be empty", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.HelpPageSampleGenerator.GetSampleObject(System.Type)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0003:Your catch maybe include some Exception", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.HelpPageSampleGenerator.TryFormatJson(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0003:Your catch maybe include some Exception", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.HelpPageSampleGenerator.TryFormatXml(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0003:Your catch maybe include some Exception", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.ObjectGenerator.GenerateObject(System.Type,System.Collections.Generic.Dictionary{System.Type,System.Object})~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0037:Remove commented code.", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0037:Remove commented code.", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.HelpPageConfig.Register(System.Web.Http.HttpConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0026:Call Extension Method As Extension", Justification = "<Pending>", Scope = "member", Target = "~M:DesenvolvimentoWebModuloII.Areas.HelpPage.ObjectGenerator.GenerateQueryable(System.Type,System.Int32,System.Collections.Generic.Dictionary{System.Type,System.Object})~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0034:Redundant field assignment", Justification = "<Pending>", Scope = "member", Target = "~F:DesenvolvimentoWebModuloII.Areas.HelpPage.ObjectGenerator.SimpleTypeObjectGenerator._index")]