//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWS_Aluno.ServiceReferenceAluno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private int NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAluno.ServicoAlunoSoap")]
    public interface ServicoAlunoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponse HelloWorld(ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponse> HelloWorldAsync(ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name CarregarAlunosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarregarAlunos", ReplyAction="*")]
        ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponse CarregarAlunos(ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarregarAlunos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponse> CarregarAlunosAsync(ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarregarAlunosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarregarAlunos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequestBody Body;
        
        public CarregarAlunosRequest() {
        }
        
        public CarregarAlunosRequest(ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CarregarAlunosRequestBody {
        
        public CarregarAlunosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarregarAlunosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarregarAlunosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponseBody Body;
        
        public CarregarAlunosResponse() {
        }
        
        public CarregarAlunosResponse(ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CarregarAlunosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWS_Aluno.ServiceReferenceAluno.Aluno[] CarregarAlunosResult;
        
        public CarregarAlunosResponseBody() {
        }
        
        public CarregarAlunosResponseBody(ClienteWS_Aluno.ServiceReferenceAluno.Aluno[] CarregarAlunosResult) {
            this.CarregarAlunosResult = CarregarAlunosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoAlunoSoapChannel : ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoAlunoSoapClient : System.ServiceModel.ClientBase<ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap>, ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap {
        
        public ServicoAlunoSoapClient() {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponse ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap.HelloWorld(ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest inValue = new ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest();
            inValue.Body = new ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequestBody();
            ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponse retVal = ((ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponse> ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap.HelloWorldAsync(ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldResponse> HelloWorldAsync() {
            ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest inValue = new ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequest();
            inValue.Body = new ClienteWS_Aluno.ServiceReferenceAluno.HelloWorldRequestBody();
            return ((ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponse ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap.CarregarAlunos(ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest request) {
            return base.Channel.CarregarAlunos(request);
        }
        
        public ClienteWS_Aluno.ServiceReferenceAluno.Aluno[] CarregarAlunos() {
            ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest inValue = new ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest();
            inValue.Body = new ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequestBody();
            ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponse retVal = ((ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap)(this)).CarregarAlunos(inValue);
            return retVal.Body.CarregarAlunosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponse> ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap.CarregarAlunosAsync(ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest request) {
            return base.Channel.CarregarAlunosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosResponse> CarregarAlunosAsync() {
            ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest inValue = new ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequest();
            inValue.Body = new ClienteWS_Aluno.ServiceReferenceAluno.CarregarAlunosRequestBody();
            return ((ClienteWS_Aluno.ServiceReferenceAluno.ServicoAlunoSoap)(this)).CarregarAlunosAsync(inValue);
        }
    }
}
