//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAtividade_III.Repositorio")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Nota1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Nota2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Nota3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Nota1 {
            get {
                return this.Nota1Field;
            }
            set {
                if ((this.Nota1Field.Equals(value) != true)) {
                    this.Nota1Field = value;
                    this.RaisePropertyChanged("Nota1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Nota2 {
            get {
                return this.Nota2Field;
            }
            set {
                if ((this.Nota2Field.Equals(value) != true)) {
                    this.Nota2Field = value;
                    this.RaisePropertyChanged("Nota2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Nota3 {
            get {
                return this.Nota3Field;
            }
            set {
                if ((this.Nota3Field.Equals(value) != true)) {
                    this.Nota3Field = value;
                    this.RaisePropertyChanged("Nota3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAluno.IAlunoService")]
    public interface IAlunoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ListAlunos", ReplyAction="http://tempuri.org/IAlunoService/ListAlunosResponse")]
        ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno[] ListAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ListAlunos", ReplyAction="http://tempuri.org/IAlunoService/ListAlunosResponse")]
        System.Threading.Tasks.Task<ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno[]> ListAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/GetAluno", ReplyAction="http://tempuri.org/IAlunoService/GetAlunoResponse")]
        ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno GetAluno(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/GetAluno", ReplyAction="http://tempuri.org/IAlunoService/GetAlunoResponse")]
        System.Threading.Tasks.Task<ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno> GetAlunoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/GetMedia", ReplyAction="http://tempuri.org/IAlunoService/GetMediaResponse")]
        double GetMedia(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/GetMedia", ReplyAction="http://tempuri.org/IAlunoService/GetMediaResponse")]
        System.Threading.Tasks.Task<double> GetMediaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlunoServiceChannel : ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.IAlunoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlunoServiceClient : System.ServiceModel.ClientBase<ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.IAlunoService>, ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.IAlunoService {
        
        public AlunoServiceClient() {
        }
        
        public AlunoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno[] ListAlunos() {
            return base.Channel.ListAlunos();
        }
        
        public System.Threading.Tasks.Task<ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno[]> ListAlunosAsync() {
            return base.Channel.ListAlunosAsync();
        }
        
        public ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno GetAluno(int id) {
            return base.Channel.GetAluno(id);
        }
        
        public System.Threading.Tasks.Task<ClienteWCF_ativ_III_AlunoService.ServiceReferenceAluno.Aluno> GetAlunoAsync(int id) {
            return base.Channel.GetAlunoAsync(id);
        }
        
        public double GetMedia(int id) {
            return base.Channel.GetMedia(id);
        }
        
        public System.Threading.Tasks.Task<double> GetMediaAsync(int id) {
            return base.Channel.GetMediaAsync(id);
        }
    }
}
